/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    `java-library`
    id("com.gradleup.shadow") version "8.3.9"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
    id("xyz.jpenilla.run-paper") version "3.0.2"
    id("xyz.jpenilla.resource-factory-bukkit-convention") version "1.3.1"
}

group = "me.lofro"
version = "1.0-SNAPSHOT"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
    maven { url = uri("https://repo.aikar.co/content/groups/aikar/") }

    maven("https://repo.codemc.org/repository/maven-public/") {
        name = "codemc"
    }
}


dependencies {
    paperweight.paperDevBundle("1.21.11-R0.1-SNAPSHOT")

    implementation("net.kyori:adventure-platform-bukkit:4.4.1")

	compileOnly("org.projectlombok:lombok:1.18.22")
	annotationProcessor("org.projectlombok:lombok:1.18.22")
	testCompileOnly("org.projectlombok:lombok:1.18.22")
	testAnnotationProcessor("org.projectlombok:lombok:1.18.22")

    implementation("co.aikar:acf-paper:0.5.1-SNAPSHOT")
}

tasks {
    assemble {
        dependsOn(reobfJar)
    }
    compileJava {
        options.compilerArgs.add("-parameters")
        options.isFork=true
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
         
    }
    javadoc {
        options.encoding = Charsets.UTF_8.name()
    }
    processResources {
        filteringCharset = Charsets.UTF_8.name()
    }

    shadowJar {
        relocate("co.aikar.commands", "me.lofro.acf")
        relocate("co.aikar.locales", "me.lofro.acf.locales")
    }
}

bukkitPluginYaml {
    name = "SquidOtakuGame"
    version = "1.0"
    apiVersion = "1.21"
    main = "me.lofro.game.SquidGame"
    author = "Lofro"
    website = "https://github.com/zLofro"
}
